### ISSUE TITLE
CRITICAL ISSUE: RTCBundlePolicy /  RTCOfferOptions Not Working

### ISSUE THREAD

**Issue by theDude30** [SamsungInternet/homepage-archive#5]
Hi,
I'm utilizing the twillio webRTC video component and it works great on all android chrome phones except for samsung internet.
The app.rtc example from google works in the samsung internet but the the webRTC twillio does not.
The twillio team identified that RTCBundlePolicy /  RTCOfferOptions are not supported in samsung internet.
Our Audio/Video component is officially released and some clients are complaining about this issue.
For more details: See below the issue i posted in the twillio's github
[https://github.com/twilio/twilio-video.js/issues/112](https://github.com/twilio/twilio-video.js/issues/112)
Can you please provide more information or help in finding a workaround for this issue?

Thanks.

**Comment by poshaughnessy** [comment]
Thanks, let's use https://github.com/SamsungInternet/support/issues/10.
